Repository intel/torch-xpu-ops, pull requests merged in 2025-04, with the labels that each got.

#1522 Modify CI/Nightly XPU build
  .github/workflows/_linux_build.yml
  .github/workflows/nightly_ondemand.yml
  .github/workflows/nightly_ondemand_rolling.yml
Labels: windows_ci

#1517 Enable op `Aten::_jagged_to_padded_dense_forward`
  src/ATen/native/nested/xpu/NestedTensorTransformerFunctions.cpp
  src/ATen/native/nested/xpu/sycl/NestedTensorTransformerFunctionKernels.cpp
  src/ATen/native/nested/xpu/sycl/NestedTensorTransformerFunctionKernels.h
  test/xpu/skip_list_common.py
  yaml/native/native_functions.yaml
Labels: windows_ci

#1541 Improve torch-xpu-ops codegen
  cmake/Codegen.cmake
  tools/codegen/install_xpu_headers.py
Labels: os: Windows, windows_ci

#1567 Revert install codegen header to torch/include
  cmake/Codegen.cmake
  src/ATen/CMakeLists.txt
  src/ATen/native/sparse/xpu/SparseCsrTensorMath.cpp
  src/ATen/native/xpu/Activation.cpp
  src/ATen/native/xpu/AdaptiveAveragePooling2d.cpp
  src/ATen/native/xpu/AdaptiveAveragePooling3d.cpp
  src/ATen/native/xpu/AdaptiveMaxPooling2d.cpp
  src/ATen/native/xpu/AdaptiveMaxPooling3d.cpp
  src/ATen/native/xpu/AveragePool2d.cpp
  src/ATen/native/xpu/AveragePool3d.cpp
  src/ATen/native/xpu/BinaryOps.cpp
  src/ATen/native/xpu/Col2Im.cpp
  src/ATen/native/xpu/DilatedMaxPool2d.cpp
  src/ATen/native/xpu/DilatedMaxPool3d.cpp
  src/ATen/native/xpu/Dropout.cpp
  src/ATen/native/xpu/Embedding.cpp
  src/ATen/native/xpu/EmbeddingBag.cpp
  src/ATen/native/xpu/Equal.cpp
  src/ATen/native/xpu/ForeachOpScalarList.cpp
  src/ATen/native/xpu/ForeachReduceOp.cpp
  src/ATen/native/xpu/FractionalMaxPool2d.cpp
  src/ATen/native/xpu/FractionalMaxPool3d.cpp
  src/ATen/native/xpu/Im2Col.cpp
  src/ATen/native/xpu/Indexing.cpp
  src/ATen/native/xpu/LossMultiMargin.cpp
  src/ATen/native/xpu/LossNLL.cpp
  src/ATen/native/xpu/PinnedMemoryAllocator.cpp
  src/ATen/native/xpu/RangeFactories.cpp
  src/ATen/native/xpu/ReflectionPad.cpp
  src/ATen/native/xpu/ReplicationPadding.cpp
  src/ATen/native/xpu/Resize.cpp
  src/ATen/native/xpu/SoftMax.cpp
  src/ATen/native/xpu/SummaryOps.cpp
  src/ATen/native/xpu/TensorAdvancedIndexing.cpp
  src/ATen/native/xpu/TensorFactories.cpp
  src/ATen/native/xpu/TensorShape.cpp
  src/ATen/native/xpu/TensorTopK.cpp
  src/ATen/native/xpu/TriangluarOps.cpp
  src/ATen/native/xpu/UpSampleBicubic2d.cpp
  src/ATen/native/xpu/UpSampleBilinear2d.cpp
  src/ATen/native/xpu/UpSampleLinear1d.cpp
  src/ATen/native/xpu/UpSampleNearest1d.cpp
  src/ATen/native/xpu/UpSampleNearest2d.cpp
  src/ATen/native/xpu/UpSampleNearest3d.cpp
  src/ATen/native/xpu/UpSampleTrilinear3d.cpp
  src/ATen/native/xpu/XPUScalar.cpp
  test/regressions/test_xpu_ops_header.py
  tools/codegen/install_xpu_headers.py
  tools/codegen/remove_headers.py
Labels: windows_ci

#1562 Performance optimization for geometric kernel
  src/ATen/native/xpu/sycl/DistributionTemplates.h
Labels: kernel_optimization

#1464 Add conv2d/3d depthwise backup kernels
  src/ATen/native/xpu/DepthwiseConv2d.cpp
  src/ATen/native/xpu/DepthwiseConv3d.cpp
  src/ATen/native/xpu/sycl/DepthwiseConv2dKernels.cpp
  src/ATen/native/xpu/sycl/DepthwiseConv2dKernels.h
  src/ATen/native/xpu/sycl/DepthwiseConv3dKernels.cpp
  src/ATen/native/xpu/sycl/DepthwiseConv3dKernels.h
Labels: xpu-op, windows_ci

#1375 [CI] Add xpu test for windows
  .github/workflows/_windows_ut.yml
  .github/workflows/pull.yml
  test/xpu/run_test_win_with_skip_mtl.py
  test/xpu/skip_list_win_mtl.py
Labels: windows_ci

#1553 Enable aten::fft_r2c
  src/ATen/native/xpu/SpectralOps.cpp
  src/ATen/native/xpu/XPUFallback.template
  src/ATen/native/xpu/mkl/SpectralOps.cpp
  src/ATen/native/xpu/mkl/SpectralOps.h
  src/ATen/native/xpu/sycl/FFTKernelFunctor.cpp
  src/ATen/native/xpu/sycl/FFTKernelFunctor.h
  yaml/native/native_functions.yaml
Labels: windows_ci
