Repository intel/torch-xpu-ops, pull requests merged in 2025-08, with the labels that each got.

#1705 Fix deterministic indexing with broadcast
  src/ATen/native/xpu/sycl/Indexing.cpp
  src/ATen/native/xpu/sycl/IndexingUtils.h
  test/xpu/skip_list_common.py
  test/xpu/test_indexing_xpu.py
Labels: bug

#1726 optimize embedding bag
  src/ATen/native/xpu/sycl/EmbeddingBag.cpp
  src/ATen/native/xpu/sycl/EmbeddingBag.h
Labels: kernel_optimization

#1952 Fix random build failure on codegen
  cmake/Codegen.cmake
Labels: windows_ci

#1982 Make torch-xpu-ops build depends on ATen XPU Codegen
  cmake/Codegen.cmake
  src/BuildOnLinux.cmake
  src/BuildOnWindows.cmake
Labels: windows_ci
